### ISSUE TITLE
Blank display of display on MacOs

### ISSUE THREAD

**Issue by jonoave** [MathildeFogPerez/ancestree#3]
Hello again,

Thanks again for the quick reply and help in the last issue.
I apologise for another interruption so soon again. 

So I've managed to load the files correctly into ancestree (the db-pass_productive-T_clone-pass_germ-pass.tsv file and igphyml-pass_hlp_asr.fasta files). However any clones I select seems to open with a blank display in the tree/results area. (Screenshot attached). I've tried zooming in/out, reset but there doesn't seem to be anything there

Here's details of java version:
```
java 15.0.2 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
```
My operating system is MacOs Big Sur version 11.2.3
ancestree version is v0.1.2

![Screenshot 2021-04-09 at 4 21 17 PM](https://user-images.githubusercontent.com/7349352/114194380-b4d11700-994f-11eb-89c3-9340b7baa427.png)

Thank you again for your help!

**Comment by MathildeFogPerez** [comment]
Hi again Jun! :)

Is there any error message printed into the terminal?
Could you please download and run ancestree v_0.1.3 to be sure there is no problem with the sequence ids?
Also are you using a sub sampling of the AIRR tsv file? Because AncesTree need alls sequence_ids from the newick tree present in the AIRR file too.
best,
Mathilde

**Comment by jonoave** [comment]
HI Mathilde,

Thanks for the quick reply.

1. I just tried 0.1.3, the error persists as well.
2. I was using the full AIRR file - direct outputs from changeO and IgPhyml

3. Here's the output on terminal, after pressing "Run"

```
v. 0.1.2
Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: 106
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:712)
	at ch.irb.IgGenealogicTreeViewer.MutationsGraph.setAaMutationsWithParent(MutationsGraph.java:136)
	at ch.irb.IgGenealogicTreeViewer.MutationsGraph.<init>(MutationsGraph.java:61)
	at ch.irb.IgGenealogicTreeViewer.IgTreePanel.drawNodeShapes(IgTreePanel.java:800)
	at ch.irb.IgGenealogicTreeViewer.IgTreePanel.draw(IgTreePanel.java:482)
	at ch.irb.IgGenealogicTreeViewer.IgTreePanel.paintComponent(IgTreePanel.java:364)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

# v.0.1.3
Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: 111
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:712)
	at ch.irb.IgGenealogicTreeViewer.MutationsGraph.setAaMutationsWithParent(MutationsGraph.java:136)
	at ch.irb.IgGenealogicTreeViewer.MutationsGraph.<init>(MutationsGraph.java:61)
	at ch.irb.IgGenealogicTreeViewer.IgTreePanel.drawNodeShapes(IgTreePanel.java:800)
	at ch.irb.IgGenealogicTreeViewer.IgTreePanel.draw(IgTreePanel.java:482)
	at ch.irb.IgGenealogicTreeViewer.IgTreePanel.paintComponent(IgTreePanel.java:364)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

Thank you again for your help and have a nice day.

**Comment by MathildeFogPerez** [comment]
Hi Jun-Hoe,

it seems a problem of deletions in your input sequences. I already noticed that the sequences you sent me contain a lots of deletions. The purpose of AncesTree is to analyze phylogenic trees of **full** antibodies sequences. If there are only few deletions in the FR1 it works, I can deal with it, otherwise it becomes too complicated (AncesTree uses the FRs and CDRs regions to annotate the alignment).
If you want I have a closer look to one of your family, please send me the files, I can check it tout more thoroughly.
best,

Mathilde
